services:
  - type: web_service
    name: civicx-backend
    env: node
    region: oregon
    branch: main
    root: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: CORS_ORIGIN
        value: https://urbancare-hiut.onrender.com/

  - type: static_site
    name: civicx-frontend
    branch: main
    root: frontend
    buildCommand: "npm install && npm run build"
    publishPath: frontend/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://urbancare-hiut.onrender.com/
    plan: free
services:
  - type: web
    name: civicx-backend
    env: node
    plan: free
    path: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"

staticSites:
  - name: civicx-frontend
    branch: main
    path: frontend
    buildCommand: "npm install && npm run build"
    publishPath: frontend/dist
